//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac_Kayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac_Kayit()
        {
            this.Sozlesme_Ekle = new HashSet<Sozlesme_Ekle>();
        }
    
        public int Arac_ID { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Yil { get; set; }
        public string Renk { get; set; }
        public string Yakit { get; set; }
        public decimal Gunluk_Kira_Ucreti { get; set; }
        public System.DateTime Sigorta_Bitis_Tarihi { get; set; }
        public System.DateTime Muayne_Bitis_Tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme_Ekle> Sozlesme_Ekle { get; set; }
    }
}
