//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muhasebe
    {
        public int Muhasebe_ID { get; set; }
        public int Personel_ID { get; set; }
        public decimal Toplam_Gelir { get; set; }
        public decimal Calısan_Gider { get; set; }
        public decimal Arac_Gider { get; set; }
        public decimal Sirket_Gider { get; set; }
        public decimal Toplam_Gider { get; set; }
    
        public virtual Personel_Ekle Personel_Ekle { get; set; }
    }
}
